version: '3.8'

services:
  naval_db:
    image: postgres:17-alpine
    container_name: naval_fleet_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ana_admin
      POSTGRES_PASSWORD: password_proyecto_123
      POSTGRES_DB: naval_fleet_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_naval_data:/var/lib/postgresql/data
    # --- SECCIÓN DE SYSTEM HARDENING (CIS BENCHMARKS) ---
    user: "70:70"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /run/postgresql:mode=777
      - /tmp:mode=777

volumes:
  postgres_naval_data: